/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package grafo_cliserv;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-05-22")
public class Aresta implements org.apache.thrift.TBase<Aresta, Aresta._Fields>, java.io.Serializable, Cloneable, Comparable<Aresta> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Aresta");

  private static final org.apache.thrift.protocol.TField NOME_V1_FIELD_DESC = new org.apache.thrift.protocol.TField("nomeV1", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NOME_V2_FIELD_DESC = new org.apache.thrift.protocol.TField("nomeV2", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField PESO_FIELD_DESC = new org.apache.thrift.protocol.TField("peso", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField FLAG__DIRECAO_FIELD_DESC = new org.apache.thrift.protocol.TField("flag_Direcao", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ArestaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ArestaTupleSchemeFactory();

  public int nomeV1; // required
  public int nomeV2; // required
  public double peso; // required
  public boolean flag_Direcao; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NOME_V1((short)1, "nomeV1"),
    NOME_V2((short)2, "nomeV2"),
    PESO((short)3, "peso"),
    FLAG__DIRECAO((short)4, "flag_Direcao");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NOME_V1
          return NOME_V1;
        case 2: // NOME_V2
          return NOME_V2;
        case 3: // PESO
          return PESO;
        case 4: // FLAG__DIRECAO
          return FLAG__DIRECAO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NOMEV1_ISSET_ID = 0;
  private static final int __NOMEV2_ISSET_ID = 1;
  private static final int __PESO_ISSET_ID = 2;
  private static final int __FLAG_DIRECAO_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NOME_V1, new org.apache.thrift.meta_data.FieldMetaData("nomeV1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NOME_V2, new org.apache.thrift.meta_data.FieldMetaData("nomeV2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PESO, new org.apache.thrift.meta_data.FieldMetaData("peso", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.FLAG__DIRECAO, new org.apache.thrift.meta_data.FieldMetaData("flag_Direcao", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Aresta.class, metaDataMap);
  }

  public Aresta() {
  }

  public Aresta(
    int nomeV1,
    int nomeV2,
    double peso,
    boolean flag_Direcao)
  {
    this();
    this.nomeV1 = nomeV1;
    setNomeV1IsSet(true);
    this.nomeV2 = nomeV2;
    setNomeV2IsSet(true);
    this.peso = peso;
    setPesoIsSet(true);
    this.flag_Direcao = flag_Direcao;
    setFlag_DirecaoIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Aresta(Aresta other) {
    __isset_bitfield = other.__isset_bitfield;
    this.nomeV1 = other.nomeV1;
    this.nomeV2 = other.nomeV2;
    this.peso = other.peso;
    this.flag_Direcao = other.flag_Direcao;
  }

  public Aresta deepCopy() {
    return new Aresta(this);
  }

  @Override
  public void clear() {
    setNomeV1IsSet(false);
    this.nomeV1 = 0;
    setNomeV2IsSet(false);
    this.nomeV2 = 0;
    setPesoIsSet(false);
    this.peso = 0.0;
    setFlag_DirecaoIsSet(false);
    this.flag_Direcao = false;
  }

  public int getNomeV1() {
    return this.nomeV1;
  }

  public Aresta setNomeV1(int nomeV1) {
    this.nomeV1 = nomeV1;
    setNomeV1IsSet(true);
    return this;
  }

  public void unsetNomeV1() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NOMEV1_ISSET_ID);
  }

  /** Returns true if field nomeV1 is set (has been assigned a value) and false otherwise */
  public boolean isSetNomeV1() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NOMEV1_ISSET_ID);
  }

  public void setNomeV1IsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NOMEV1_ISSET_ID, value);
  }

  public int getNomeV2() {
    return this.nomeV2;
  }

  public Aresta setNomeV2(int nomeV2) {
    this.nomeV2 = nomeV2;
    setNomeV2IsSet(true);
    return this;
  }

  public void unsetNomeV2() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NOMEV2_ISSET_ID);
  }

  /** Returns true if field nomeV2 is set (has been assigned a value) and false otherwise */
  public boolean isSetNomeV2() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NOMEV2_ISSET_ID);
  }

  public void setNomeV2IsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NOMEV2_ISSET_ID, value);
  }

  public double getPeso() {
    return this.peso;
  }

  public Aresta setPeso(double peso) {
    this.peso = peso;
    setPesoIsSet(true);
    return this;
  }

  public void unsetPeso() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PESO_ISSET_ID);
  }

  /** Returns true if field peso is set (has been assigned a value) and false otherwise */
  public boolean isSetPeso() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PESO_ISSET_ID);
  }

  public void setPesoIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PESO_ISSET_ID, value);
  }

  public boolean isFlag_Direcao() {
    return this.flag_Direcao;
  }

  public Aresta setFlag_Direcao(boolean flag_Direcao) {
    this.flag_Direcao = flag_Direcao;
    setFlag_DirecaoIsSet(true);
    return this;
  }

  public void unsetFlag_Direcao() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FLAG_DIRECAO_ISSET_ID);
  }

  /** Returns true if field flag_Direcao is set (has been assigned a value) and false otherwise */
  public boolean isSetFlag_Direcao() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FLAG_DIRECAO_ISSET_ID);
  }

  public void setFlag_DirecaoIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FLAG_DIRECAO_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case NOME_V1:
      if (value == null) {
        unsetNomeV1();
      } else {
        setNomeV1((java.lang.Integer)value);
      }
      break;

    case NOME_V2:
      if (value == null) {
        unsetNomeV2();
      } else {
        setNomeV2((java.lang.Integer)value);
      }
      break;

    case PESO:
      if (value == null) {
        unsetPeso();
      } else {
        setPeso((java.lang.Double)value);
      }
      break;

    case FLAG__DIRECAO:
      if (value == null) {
        unsetFlag_Direcao();
      } else {
        setFlag_Direcao((java.lang.Boolean)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NOME_V1:
      return getNomeV1();

    case NOME_V2:
      return getNomeV2();

    case PESO:
      return getPeso();

    case FLAG__DIRECAO:
      return isFlag_Direcao();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NOME_V1:
      return isSetNomeV1();
    case NOME_V2:
      return isSetNomeV2();
    case PESO:
      return isSetPeso();
    case FLAG__DIRECAO:
      return isSetFlag_Direcao();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Aresta)
      return this.equals((Aresta)that);
    return false;
  }

  public boolean equals(Aresta that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_nomeV1 = true;
    boolean that_present_nomeV1 = true;
    if (this_present_nomeV1 || that_present_nomeV1) {
      if (!(this_present_nomeV1 && that_present_nomeV1))
        return false;
      if (this.nomeV1 != that.nomeV1)
        return false;
    }

    boolean this_present_nomeV2 = true;
    boolean that_present_nomeV2 = true;
    if (this_present_nomeV2 || that_present_nomeV2) {
      if (!(this_present_nomeV2 && that_present_nomeV2))
        return false;
      if (this.nomeV2 != that.nomeV2)
        return false;
    }

    boolean this_present_peso = true;
    boolean that_present_peso = true;
    if (this_present_peso || that_present_peso) {
      if (!(this_present_peso && that_present_peso))
        return false;
      if (this.peso != that.peso)
        return false;
    }

    boolean this_present_flag_Direcao = true;
    boolean that_present_flag_Direcao = true;
    if (this_present_flag_Direcao || that_present_flag_Direcao) {
      if (!(this_present_flag_Direcao && that_present_flag_Direcao))
        return false;
      if (this.flag_Direcao != that.flag_Direcao)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + nomeV1;

    hashCode = hashCode * 8191 + nomeV2;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(peso);

    hashCode = hashCode * 8191 + ((flag_Direcao) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(Aresta other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetNomeV1()).compareTo(other.isSetNomeV1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNomeV1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nomeV1, other.nomeV1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNomeV2()).compareTo(other.isSetNomeV2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNomeV2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nomeV2, other.nomeV2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPeso()).compareTo(other.isSetPeso());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPeso()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.peso, other.peso);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFlag_Direcao()).compareTo(other.isSetFlag_Direcao());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFlag_Direcao()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.flag_Direcao, other.flag_Direcao);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Aresta(");
    boolean first = true;

    sb.append("nomeV1:");
    sb.append(this.nomeV1);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nomeV2:");
    sb.append(this.nomeV2);
    first = false;
    if (!first) sb.append(", ");
    sb.append("peso:");
    sb.append(this.peso);
    first = false;
    if (!first) sb.append(", ");
    sb.append("flag_Direcao:");
    sb.append(this.flag_Direcao);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ArestaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ArestaStandardScheme getScheme() {
      return new ArestaStandardScheme();
    }
  }

  private static class ArestaStandardScheme extends org.apache.thrift.scheme.StandardScheme<Aresta> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Aresta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NOME_V1
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nomeV1 = iprot.readI32();
              struct.setNomeV1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NOME_V2
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nomeV2 = iprot.readI32();
              struct.setNomeV2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PESO
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.peso = iprot.readDouble();
              struct.setPesoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FLAG__DIRECAO
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.flag_Direcao = iprot.readBool();
              struct.setFlag_DirecaoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Aresta struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NOME_V1_FIELD_DESC);
      oprot.writeI32(struct.nomeV1);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NOME_V2_FIELD_DESC);
      oprot.writeI32(struct.nomeV2);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PESO_FIELD_DESC);
      oprot.writeDouble(struct.peso);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(FLAG__DIRECAO_FIELD_DESC);
      oprot.writeBool(struct.flag_Direcao);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ArestaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ArestaTupleScheme getScheme() {
      return new ArestaTupleScheme();
    }
  }

  private static class ArestaTupleScheme extends org.apache.thrift.scheme.TupleScheme<Aresta> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Aresta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNomeV1()) {
        optionals.set(0);
      }
      if (struct.isSetNomeV2()) {
        optionals.set(1);
      }
      if (struct.isSetPeso()) {
        optionals.set(2);
      }
      if (struct.isSetFlag_Direcao()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetNomeV1()) {
        oprot.writeI32(struct.nomeV1);
      }
      if (struct.isSetNomeV2()) {
        oprot.writeI32(struct.nomeV2);
      }
      if (struct.isSetPeso()) {
        oprot.writeDouble(struct.peso);
      }
      if (struct.isSetFlag_Direcao()) {
        oprot.writeBool(struct.flag_Direcao);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Aresta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.nomeV1 = iprot.readI32();
        struct.setNomeV1IsSet(true);
      }
      if (incoming.get(1)) {
        struct.nomeV2 = iprot.readI32();
        struct.setNomeV2IsSet(true);
      }
      if (incoming.get(2)) {
        struct.peso = iprot.readDouble();
        struct.setPesoIsSet(true);
      }
      if (incoming.get(3)) {
        struct.flag_Direcao = iprot.readBool();
        struct.setFlag_DirecaoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
